const path = require("node:path");

const VIEW_TYPE = "aiexport.sidebarView";

const IGNORED_NAMES = new Set([
	"node_modules",
	".git",
	".vscode",
	".cursor",
	"dist",
	"out",
	"build",
	".next",
	"__pycache__",
	".DS_Store",
	"package-lock.json",
	"yarn.lock",
	"bun.lockb",
	"pnpm-lock.yaml",
	".env",
	".vsix",
	"thumbs.db",
	".turbo",
	".vercel",
	".svelte-kit",
	".nuxt",
	"coverage",
]);

const ALLOWED_HIDDEN_NAMES = new Set([
	".env.example",
	".gitignore",
	".editorconfig",
	".prettierrc",
]);

const BINARY_EXTENSIONS = new Set([
	".png",
	".jpg",
	".jpeg",
	".gif",
	".ico",
	".svg",
	".webp",
	".avif",
	".mp3",
	".mp4",
	".wav",
	".avi",
	".mov",
	".webm",
	".ogg",
	".zip",
	".tar",
	".gz",
	".rar",
	".7z",
	".bz2",
	".exe",
	".dll",
	".so",
	".dylib",
	".pdf",
	".doc",
	".docx",
	".xls",
	".xlsx",
	".ppt",
	".pptx",
	".woff",
	".woff2",
	".ttf",
	".eot",
	".otf",
	".vsix",
	".map",
	".lock",
	".sqlite",
	".db",
]);

/** Map file extensions to comment syntax for stripping */
const COMMENT_SYNTAX = {
	cStyle: {
		line: "//",
		blockStart: "/*",
		blockEnd: "*/",
	},
	hash: {
		line: "#",
		blockStart: null,
		blockEnd: null,
	},
	html: {
		line: null,
		blockStart: "<!--",
		blockEnd: "-->",
	},
	lua: {
		line: "--",
		blockStart: "--[[",
		blockEnd: "]]",
	},
	sql: {
		line: "--",
		blockStart: "/*",
		blockEnd: "*/",
	},
};

const EXTENSION_COMMENT_MAP = {
	".js": "cStyle",
	".jsx": "cStyle",
	".ts": "cStyle",
	".tsx": "cStyle",
	".mjs": "cStyle",
	".cjs": "cStyle",
	".java": "cStyle",
	".c": "cStyle",
	".cpp": "cStyle",
	".h": "cStyle",
	".hpp": "cStyle",
	".cs": "cStyle",
	".go": "cStyle",
	".rs": "cStyle",
	".swift": "cStyle",
	".kt": "cStyle",
	".kts": "cStyle",
	".scala": "cStyle",
	".dart": "cStyle",
	".css": "cStyle",
	".scss": "cStyle",
	".less": "cStyle",
	".php": "cStyle",
	".json": null,
	".jsonc": "cStyle",
	".py": "hash",
	".rb": "hash",
	".sh": "hash",
	".bash": "hash",
	".zsh": "hash",
	".yml": "hash",
	".yaml": "hash",
	".toml": "hash",
	".dockerfile": "hash",
	".r": "hash",
	".pl": "hash",
	".pm": "hash",
	".html": "html",
	".htm": "html",
	".xml": "html",
	".vue": "html",
	".svelte": "html",
	".lua": "lua",
	".sql": "sql",
};

const MAX_FILE_SIZE_BYTES = 1024 * 1024; // 1 MB

const WEBVIEW_ASSET_PATHS = {
	css: path.join("media", "sidebar.css"),
	js: path.join("media", "sidebar.js"),
};

module.exports = {
	ALLOWED_HIDDEN_NAMES,
	BINARY_EXTENSIONS,
	COMMENT_SYNTAX,
	EXTENSION_COMMENT_MAP,
	IGNORED_NAMES,
	MAX_FILE_SIZE_BYTES,
	VIEW_TYPE,
	WEBVIEW_ASSET_PATHS,
};
